### ISSUE TITLE
startpage FATES platform

### ISSUE THREAD

**Issue by peterhor** [NorESMhub/noresm-land-sites-platform#106]
When you start the platform on Docker under localhost:8080, it would be nice to get a complete overview of the running, finished and executed cases. Currently you have to remember which site you have already run (ex. BOR1), click it, and there is the overview for specific site.

**Comment by lasseke** [comment]
I think this is an excellent suggestion (tagging @ka7eh just in case, not a priority)

**Comment by ka7eh** [comment]
Fixed in https://github.com/NorESMhub/noresm-lsp-ui/pull/11.
