### ISSUE TITLE
Add `nc-time-axis` dependency (optional for `xarray`)

### ISSUE THREAD

**Issue by lasseke** [NorESMhub/noresm-land-sites-platform#126]
In the current version of `xarray` we use, it is not possible to plot `cftime.datetime` type time axes without prior conversion to a different format. Error message from the inbuilt `xarray.core.dataarray.DataArray` `plot()` function:

```
ImportError: Plotting of arrays of cftime.datetime objects or arrays indexed by cftime.datetime objects requires the optional `nc-time-axis` (v1.2.0 or later) package.
```

Our previous workaround was to convert them to `pandas.core.indexes.datetimes.DatetimeIndex` type as follows:

```
nc_data_h0["time"] = nc_data_h0.indexes["time"].to_datetimeindex()
```

However, this does not work when the simulation dates exceed the maximum date limit for this data type ([see here](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timestamp-limitations)). Installing the following package fixes this issue and makes conversion obsolete (within Jupyter env):

```
python3 -m pip install nc-time-axis
```

Could we add this to the dependencies or adjust the `xarray` version?

**Comment by ka7eh** [comment]
Resolved in #127
