### ISSUE TITLE
Edit button broke

### ISSUE THREAD

**Issue by lasseke** [NorESMhub/noresm-land-sites-platform#133]
**Describe the bug**
The `Edit` button in the GUI stopped working. Clicking it doesn't trigger any action. No errors are logged to the docker console or web console.

**To Reproduce**
1. Create a case
2. Click on "Edit"

**Expected behavior**
Being able to edit the case :)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: SHA [424d614](https://github.com/NorESMhub/noresm-land-sites-platform/commit/424d61452a30a23e4ff4944b7d7761ee01b0b960)

**Comment by ka7eh** [comment]
Fixed in https://github.com/NorESMhub/noresm-lsp-ui/commit/6dcfb8b0ca5382ea93e5c339ace3d6bee6222e85.
