### ISSUE TITLE
Adding a simple instruction in the documentation on how to direct access to the container for model developer

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/noresm-land-sites-platform#140]
As a developer, I find it is quite handy to directly access to the model code in the container, change the code and recompile and run the model through terminal.  Two ways to do that:

- Option 1:
` sudo docker container exec -u 0 -it <container ID> bash `

- Option 2:
 Use the terminal in jupyternote book. But I notice that the model code folder is not linked to jupyter notebook container (see https://github.com/NorESMhub/noresm-land-sites-platform/blob/7ebae623ab0d050a49af8a7071c2e1d8ba2fec93/docker-compose.yaml#L65). So, in the current version of the platform, it seems impossible to see the model code folder through jupyter notebook container?

@ka7eh: Could we add a model code folder to jupyter notebook container? 
@evalieungh: Could we add a few sentences in the documentation to instruct developer how to access to the model code? I could help with this if needed.

**Comment by evalieungh** [comment]
Thanks for the suggestion, @huitang-earth. Writing this more clearly in the docs has been on my to-do-list, but it isn't 100% clear to me what methods are best for developers & advanced users to use. It would be great if we could e.g. do everything through JupyterLab (notebooks and terminal there). Would that be possible, @ka7eh ? If it is, this might not be our first priority before publication but it would be nice to be able to make adjustments to input data, model code, and other things directly through JupyterLab.

**Comment by ka7eh** [comment]
@huitang-earth @evalieungh right now we cannot add this option to jupyter because the jupyter image is separate from the model (api) one. We can add jupyter to the api image and use the same image for both, but it needs some modification.

The best option is to add the instruction to the docs. You can use these commands:

If you have a `.env` file in the project root with `HOST_USER` set in it, use this:
    docker-compose exec -u <host_user_value> api bash
Otherwise, use this:
    docker-compose exec api bash

This will open a terminal in `/ctsm-api`. The model is in `/ctsm-api/resources/ctsm`, and cases created with the api go in `/ctsm-api/resources/cases`, and their data in `/ctsm-api/resources/data/<case-id>`. The build, run, and archive folders are put inside the case folder. Shared data goes in `/ctsm-api/resources/data/shared`.

**Comment by evalieungh** [comment]
Thanks for explaining, @ka7eh. I can add this to the documentation during the next few days.

**Comment by evalieungh** [comment]
I've added this to my draft PR #148 now, but I'm not sure I fully understand. I wonder if it might be nice to create an illustration of advanced use, similar to [this figure](https://noresmhub.github.io/noresm-land-sites-platform/img/user-interfaces-and-architecture-Page-1.png) but with a user icon on the left and arrows going from the user and to the relevant parts to access via terminals.

**Comment by ka7eh** [comment]
> I've added this to my draft PR #148 now, but I'm not sure I fully understand. I wonder if it might be nice to create an illustration of advanced use, similar to [this figure](https://noresmhub.github.io/noresm-land-sites-platform/img/user-interfaces-and-architecture-Page-1.png) but with a user icon on the left and arrows going from the user and to the relevant parts to access via terminals.

The main goal is to tell advance users how they can get into the container and where things are. It'd be good to include the paths I mentioned above in the docs. Assuming they know how to use CTSM/NorESM, they should be good after that.

We can still create a graphic that shows the structure of the model and its input and output paths within the container.
