### ISSUE TITLE
Developing a branch for moss & lichen work

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/noresm-land-sites-platform#141]
Just to put it as placeholder to remind me. 

I will slowly create a branch of the platform specifically for moss model development and testing. The time frame could be 1-2 months.

**Comment by evalieungh** [comment]
Exciting! It would be really cool to easily include moss or lichen PFTs in the LSP.

**Comment by evalieungh** [comment]
Closing this, we can continue discussion on #166
