### ISSUE TITLE
Is "overwrites/cime" folder redundant now if we use NUOPC as the coupler?

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/noresm-land-sites-platform#144]
We will use the files from "[cdeps/datm/cime_config](https://github.com/NorESMhub/noresm-land-sites-platform/tree/main/resources/overwrites/components/cdeps/datm/cime_config)" instead in newer versions of ctsm.

So the files in the [cime folder ](https://github.com/NorESMhub/noresm-land-sites-platform/tree/main/resources/overwrites/cime) can be discarded?

**Comment by ka7eh** [comment]
This is resolved with the latest changes in https://github.com/NorESMhub/ctsm-api/pull/12.
