### ISSUE TITLE
Failed to compose  api-1 and tasks-1

### ISSUE THREAD

**Issue by peterhor** [NorESMhub/noresm-land-sites-platform#153]
During the docker compose process, the containers "api-1" and "tasks-1" fail to finish composing (exit with code 1 and 2), and keep restarting.
The issue is same for Windows 11 OS (build 22000.1219) and macOS (arm ref. @MichalTorma).

the code before exiting is as follows:

noresm-land-sites-platform-tasks-1     | Usage: celery [OPTIONS] COMMAND [ARGS]...
noresm-land-sites-platform-tasks-1     | Try 'celery --help' for help.
noresm-land-sites-platform-tasks-1     |
noresm-land-sites-platform-tasks-1     | Error: Invalid value for '-A' / '--app':
noresm-land-sites-platform-tasks-1     | Unable to load celery application.
noresm-land-sites-platform-tasks-1     | While trying to load the module app the following error occurred:
noresm-land-sites-platform-tasks-1     | Traceback (most recent call last):
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
noresm-land-sites-platform-tasks-1     |     module = imp(module_name, package=package, **kwargs)
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/celery/utils/imports.py", line 105, in import_from_cwd
noresm-land-sites-platform-tasks-1     |     return imp(module, package=package)
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
noresm-land-sites-platform-tasks-1     |     return _bootstrap._gcd_import(name[level:], package, level)
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/__init__.py", line 1, in <module>
noresm-land-sites-platform-tasks-1     |     from app.tasks.celery_app import celery_app
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/tasks/__init__.py", line 1, in <module>
noresm-land-sites-platform-tasks-1     |     from .cases import create_case, run_case
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/tasks/cases.py", line 14, in <module>
noresm-land-sites-platform-tasks-1     |     from app import crud, models, schemas
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/crud/__init__.py", line 1, in <module>
noresm-land-sites-platform-tasks-1     |     from .cases import case
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/crud/cases.py", line 7, in <module>
noresm-land-sites-platform-tasks-1     |     from app import models, schemas, tasks
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/schemas/__init__.py", line 1, in <module>
noresm-land-sites-platform-tasks-1     |     from .cases import (
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/schemas/cases.py", line 12, in <module>
noresm-land-sites-platform-tasks-1     |     from app.core import settings
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/core/__init__.py", line 3, in <module>
noresm-land-sites-platform-tasks-1     |     settings = get_settings()
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/core/config.py", line 79, in get_settings
noresm-land-sites-platform-tasks-1     |     return Settings()
noresm-land-sites-platform-tasks-1     |   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
noresm-land-sites-platform-tasks-1     |   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
noresm-land-sites-platform-tasks-1     | pydantic.error_wrappers.ValidationError: 1 validation error for Settings
noresm-land-sites-platform-tasks-1     | CTSM_TAG
noresm-land-sites-platform-tasks-1     |   field required (type=value_error.missing)
noresm-land-sites-platform-tasks-1     |
noresm-land-sites-platform-tasks-1     | During handling of the above exception, another exception occurred:
noresm-land-sites-platform-tasks-1     |
noresm-land-sites-platform-tasks-1     | Traceback (most recent call last):
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/celery/bin/celery.py", line 57, in convert
noresm-land-sites-platform-tasks-1     |     return find_app(value)
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/celery/app/utils.py", line 384, in find_app
noresm-land-sites-platform-tasks-1     |     sym = symbol_by_name(app, imp=imp)
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/kombu/utils/imports.py", line 58, in symbol_by_name
noresm-land-sites-platform-tasks-1     |     reraise(ValueError,
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/kombu/exceptions.py", line 21, in reraise
noresm-land-sites-platform-tasks-1     |     raise value.with_traceback(tb)
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
noresm-land-sites-platform-tasks-1     |     module = imp(module_name, package=package, **kwargs)
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/celery/utils/imports.py", line 105, in import_from_cwd
noresm-land-sites-platform-tasks-1     |     return imp(module, package=package)
noresm-land-sites-platform-tasks-1     |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
noresm-land-sites-platform-tasks-1     |     return _bootstrap._gcd_import(name[level:], package, level)
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
noresm-land-sites-platform-tasks-1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/__init__.py", line 1, in <module>
noresm-land-sites-platform-tasks-1     |     from app.tasks.celery_app import celery_app
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/tasks/__init__.py", line 1, in <module>
noresm-land-sites-platform-tasks-1     |     from .cases import create_case, run_case
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/tasks/cases.py", line 14, in <module>
noresm-land-sites-platform-tasks-1     |     from app import crud, models, schemas
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/crud/__init__.py", line 1, in <module>
noresm-land-sites-platform-tasks-1     |     from .cases import case
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/crud/cases.py", line 7, in <module>
noresm-land-sites-platform-tasks-1     |     from app import models, schemas, tasks
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/schemas/__init__.py", line 1, in <module>
noresm-land-sites-platform-tasks-1     |     from .cases import (
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/schemas/cases.py", line 12, in <module>
noresm-land-sites-platform-tasks-1     |     from app.core import settings
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/core/__init__.py", line 3, in <module>
noresm-land-sites-platform-tasks-1     |     settings = get_settings()
noresm-land-sites-platform-tasks-1     |   File "/ctsm-api/app/core/config.py", line 79, in get_settings
noresm-land-sites-platform-tasks-1     |     return Settings()
noresm-land-sites-platform-tasks-1     |   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
noresm-land-sites-platform-tasks-1     |   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
noresm-land-sites-platform-tasks-1     | ValueError: Couldn't import 'app': 1 validation error for Settings
noresm-land-sites-platform-tasks-1     | CTSM_TAG
noresm-land-sites-platform-tasks-1     |   field required (type=value_error.missing)
noresm-land-sites-platform-tasks-1     |
noresm-land-sites-platform-tasks-1 exited with code 2

![image](https://user-images.githubusercontent.com/21362739/200907343-04e50bf0-d90d-4782-a509-7e2bea0bc7c9.png)

**Comment by evalieungh** [comment]
Is this still a problem, @peterhor ? Were you able to test again, checking that Docker is 'clean' beforehand?

**Comment by peterhor** [comment]
This issue was resolved by the suggestion above
