### ISSUE TITLE
VCG notebook dictionary bug

### ISSUE THREAD

**Issue by evalieungh** [NorESMhub/noresm-land-sites-platform#159]
**Describe the bug**
Listing sites in the compare_model_to_vcg_obs notebook is broken. A recent change in resources/config/sites.json removed the "group" variable which is used in that notebook to list the sites at the beginning. 

**To Reproduce**
1. Start LSP, run a VCG case
2. Go to Jupyterlab, open compare_model_to_vcg_obs notebook 
3. run second cell to list the VCG/SeedClim sites

**Expected behavior**
The notebook cell should list the Vestland Climate Grid (also called SeedClim) sites

**Desktop (please complete the following information):**
NREC, Ubuntu, LSP most recent commit [87cedd5](https://github.com/NorESMhub/noresm-land-sites-platform/commit/87cedd55e9a1792647a661e6287c57f9419d7723)

**Additional context**
Perhaps easiest to fix by changing the notebook to use the one under notebooks/model_output_analysis/dicts

**Comment by lasseke** [comment]
Fixed in 7d7d8327a31560f8a85643a00edc8e6fd33784fd
