### ISSUE TITLE
A question / slow performance on M1 mac

### ISSUE THREAD

**Issue by mvdebolskiy** [NorESMhub/noresm-land-sites-platform#162]
### Write you question here:

Norman Steinert tried to run the platform with an apple M1 processor and experienced extremely slow performance to the point that docker was giving up on the containers. I am pretty sure that overwrites for `.cime` in terms of compilers and dependencies are needed to fix this. I'll try to look into that during the holidays.

**Comment by evalieungh** [comment]
Hello, 
while the problem with this type of Mac might be beyond us to solve, an alternative for UiB and UiO users could be a virtual machine on [NREC](https://docs.nrec.no/intro.html#who-can-use-the-nrec-cloud). It is a bit cumbersome to set up properly, but we have experience with it and once it's set up the LSP works normal. (Using a virtual machine also has the benefit that running longer simulations will not take up 90% of your RAM for multiple workdays...)

Students etc can get a basic machine and some storage without applying, I think, and it's possible to apply for more resources if necessary. 

1. Creating a VM on NREC is documented both in the [NREC user guide](https://docs.nrec.no/create-virtual-machine.html), [this issue](https://github.com/NorESMhub/noresm-land-sites-platform/issues/156) and in [Emiliano Gelati's instructions for an older version of the LSP](https://github.com/NorESMhub/noresm-land-sites-platform/tree/archive/.machine/NREC_VM_setup). Use a `GOLD Ubuntu 22.04 LTS` base image, and dualstack network.
2. To get enough storage space for more than short test simulations, you need to attach a "Volume" to the virtual machine. See [my issue](https://github.com/NorESMhub/noresm-land-sites-platform/issues/157) to see how I did it...
3. Using the virtual machine is outlined in the [LSP documentation](https://noresmhub.github.io/noresm-land-sites-platform/documentation/#ssh-tunneling-with-example-for-nrec)

If this is too confusing, just ask and I can try to help.

**Comment by mvdebolskiy** [comment]
We figure it out. Seems like MacOs older than 15.5 was slowing things down. It also helps to turn on Virtualization Framework in the Settings\Experimental Features in Docker. And last, adjust memory, disk space, and CPU in the Settings\Resources.

**Comment by lasseke** [comment]
Awesome, great work @mvdebolskiy! We should add your solution to the documentation.

**Comment by evalieungh** [comment]
Great that you found a solution. I've added a link to this issue in PR draft https://github.com/NorESMhub/noresm-land-sites-platform/pull/167
