### ISSUE TITLE
Future feature idea (💡): let users change arbitrary FATES parameter settings via bokeh app

### ISSUE THREAD

**Issue by lasseke** [NorESMhub/noresm-land-sites-platform#92]
Leaving this here as a possible inspiration for future releases as the implementation now would be too time-consuming. 

Until now, we have been discussing making a sub-selection of changeable parameters for running the model via the platform. While this is generally good for simplification and inexperienced users, implementing a user-friendly way to change any FATES parameter via the graphical interface/settings files could add great scientific value.

One possible way would be to directly read the parameters and values from the default files instead of taking the detour over customized JSON dictionaries. Then, we could add a new section "additional_parameters" to the platform settings files and the bokeh app that accepts/generates any valid parameter-value combination.

**Comment by evalieungh** [comment]
Guess this is in part taken care of with the additional 'Advanced' box for CLM namelist options.
